//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularjsMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_M
    {
        public string SupId { get; set; }
        public string SupName { get; set; }
        public string SupShortName { get; set; }
        public string ContactPerson { get; set; }
        public string ShipType { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string VendorCreatDate { get; set; }
        public string IST_Date { get; set; }
        public string IEN_Date { get; set; }
        public string StopTranDate_S { get; set; }
        public string StopTranDate_E { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DataDate { get; set; }
        public string UserID { get; set; }
    }
}
