//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularjsPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_D
    {
        public string SupId { get; set; }
        public string FirmNo { get; set; }
        public string FirmName { get; set; }
        public string FirmShortNo { get; set; }
        public string MapType { get; set; }
        public string ContactPerson { get; set; }
        public string OrderType { get; set; }
        public string ArrivalDays { get; set; }
        public string FirmType { get; set; }
        public string VendorCreatDate { get; set; }
        public string DataPeriod_S { get; set; }
        public string DataPeriod_E { get; set; }
        public string ContactDate_S { get; set; }
        public string ContactDate_E { get; set; }
        public string SettleType { get; set; }
        public string PayType { get; set; }
        public string BankCode { get; set; }
        public string RemitAcno { get; set; }
        public string PayArea { get; set; }
        public string CheckDays { get; set; }
        public string RefundType { get; set; }
        public string InvoiceType { get; set; }
        public string AddressDist { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string DFLG { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DataDate { get; set; }
        public string UserID { get; set; }
    }
}
